# version: '3.8'

services:
  # 数据库服务
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: linkinbio
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 后端 API 服务
  api:
    build:
      context: ./api
      dockerfile: Dockerfile # 开发时使用这个 Dockerfile
    restart: unless-stopped
    ports:
      - "4000:4000"
    volumes:
      - ./api:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://admin:password123@db:5432/linkinbio?schema=public"

  # 前端 Web 服务
  web:
    build:
      context: ./web
      dockerfile: Dockerfile # 开发时使用这个 Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
      - /app/node_modules
    depends_on:
      - api
    environment:
      # 在容器内，前端需要知道 API 的地址
      NEXT_PUBLIC_API_URL: "http://localhost:4000"

volumes:
  postgres_data:
    driver: local