name: Continuous Integration - Build, Test, and Push Images

on:
  pull_request:
    branches: [ "main" ]

jobs:
  validate-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Backend Unit & Integration Tests
        run: |
          echo "将来在这里运行后端测试..."
          
      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push API production image
        uses: docker/build-push-action@v5
        with:
          context: ./api
          file: ./api/Dockerfile.prod
          push: true
          # 【已修正】使用官方 toLowerCase() 函数，这是正确的语法
          tags: ghcr.io/${{ toLowerCase(github.repository_owner) }}/${{ github.event.repository.name }}/api:latest

      - name: Build and push Web production image
        uses: docker/build-push-action@v5
        with:
          context: ./web
          file: ./web/Dockerfile.prod
          push: true
          # 【已修正】使用官方 toLowerCase() 函数，这是正确的语法
          tags: ghcr.io/${{ toLowerCase(github.repository_owner) }}/${{ github.event.repository.name }}/web:latest