name: Continuous Integration - Build, Test, and Push Images

on:
  pull_request:
    branches: [ "main" ]

jobs:
  validate-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      # 新增步骤：将仓库所有者（您的用户名）转换为小写，并设置为输出变量
      - name: Set owner to lowercase
        id: string
        run: echo "owner_lc=${{ github.repository_owner,, }}" >> $GITHUB_OUTPUT

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Backend Unit & Integration Tests
        run: |
          echo "将来在这里运行后端测试..."

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push API production image
        uses: docker/build-push-action@v5
        with:
          context: ./api
          file: ./api/Dockerfile.prod
          push: true
          # 【修正】使用转换后的小写用户名
          tags: ghcr.io/${{ steps.string.outputs.owner_lc }}/${{ github.event.repository.name }}/api:latest

      - name: Build and push Web production image
        uses: docker/build-push-action@v5
        with:
          context: ./web
          file: ./web/Dockerfile.prod
          push: true
          # 【修正】使用转换后的小写用户名
          tags: ghcr.io/${{ steps.string.outputs.owner_lc }}/${{ github.event.repository.name }}/web:latest