name: Main CI/CD Workflow

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  build-and-validate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 【核心修正】新增一个独立的步骤，使用 Shell 命令生成小写用户名
      - name: Generate lowercase owner name
        id: strings
        run: echo "owner=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Log in to the GitHub Container Registry
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push API production image
        uses: docker/build-push-action@v5
        with:
          context: ./api
          file: ./api/Dockerfile.prod
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          # 【核心修正】使用上一步生成的输出变量
          tags: ghcr.io/${{ steps.strings.outputs.owner }}/${{ github.event.repository.name }}/api:latest

      - name: Build and push Web production image
        uses: docker/build-push-action@v5
        with:
          context: ./web
          file: ./web/Dockerfile.prod
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          # 【核心修正】使用上一步生成的输出变量
          tags: ghcr.io/${{ steps.strings.outputs.owner }}/${{ github.event.repository.name }}/web:latest
          
      - name: Trigger Render Backend Deploy
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"